# Generated by Django 2.1.1 on 2018-09-17 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    # dependencies = [
    #     ('professionalInformation', '0001_initial'),
    #     ('address', '0001_initial'),
    # ]

    operations = [
        migrations.CreateModel(
            name='Travels',
            fields=[
                ('Id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverId', models.CharField(max_length=10)),
                ('numPassengers',  models.CharField(max_length=11)),
                ('date', models.CharField(max_length=200)),
                ('startTime', models.CharField(max_length=200)),
                ('finishTime', models.CharField(max_length=200)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('city', models.CharField(max_length=200)),
                ('ubication', models.CharField(max_length=200)),
                ('postalCode', models.CharField(max_length=200))
            ],
        ),
    ]
