# Generated by Django 2.1.1 on 2018-09-17 02:44

from django.db import migrations, models
import travels.validations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='travels',
    #         name='CPF',
    #         field=models.CharField(max_length=13, unique=True, validators=[travels.validations.validate_cpf, travels.validations.validate_cpf_length]),
    #     ),
    #     migrations.AlterField(
    #         model_name='travels',
    #         name='RG',
    #         field=models.CharField(max_length=11, unique=True, validators=[travels.validations.validate_rg_length]),
    #     ),
    # ]
