# Generated by Django 3.0.2 on 2021-02-12 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_favorites'),
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoration',
            fields=[
                ('slug', models.SlugField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valorations', to='profiles.Profile')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valorations', to='travels.Travels')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
