# Generated by Django 3.0.2 on 2021-02-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_auto_20210204_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travels',
            name='numPassengers',
            field=models.CharField(default='2', max_length=11),
        ),
        migrations.AlterField(
            model_name='travels',
            name='postalCode',
            field=models.CharField(default='0000', max_length=200),
        ),
    ]
