# Generated by Django 3.0.2 on 2021-02-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_travels_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travels',
            name='slug',
            field=models.SlugField(default='', max_length=255),
        ),
    ]
