# Generated by Django 3.0.2 on 2021-02-15 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_valoration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valoration',
            options={},
        ),
        migrations.RenameField(
            model_name='valoration',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RemoveField(
            model_name='valoration',
            name='updated_at',
        ),
    ]
