# Generated by Django 3.0.2 on 2021-02-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_auto_20210209_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travels',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
    ]
