# Generated by Django 3.0.2 on 2021-02-15 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_auto_20210215_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valoration',
            old_name='travel',
            new_name='travel_slug',
        ),
    ]
