# Generated by Django 3.0.2 on 2021-02-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('surname', models.CharField(default='', max_length=200)),
                ('tlf', models.CharField(default=0, max_length=20)),
                ('address', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
