# Generated by Django 3.0.2 on 2021-02-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='normal', max_length=100)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
    ]
