# Generated by Django 3.0.2 on 2021-02-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='name',
            field=models.CharField(default='normal', max_length=100),
        ),
    ]
