# Generated by Django 3.0.2 on 2021-02-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categories_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='type',
            new_name='image',
        ),
    ]
